### ISSUE TITLE
Original sources?

### ISSUE THREAD

**Issue by XVincentX** [geek/frontend#1]
Hey - Vincenzo from LunchBadger here!

It seems like the sources you released are more an artifact (produced by Webpack or Browserify) rather than the original source files. Would it be possible to include these into the repository so that reasoning about these would be way more easy?

Thanks!

**Comment by geek** [comment]
Fixed via https://github.com/geek/frontend/commit/ff3308de8da590fac18a4fb9048cad6f23446489

**Comment by XVincentX** [comment]
Thanks a lot! That simplifies the things a lot!
